### ISSUE TITLE
Did not find apps in playstore. We can not download apps with Links provided in REDME

### ISSUE THREAD

**Issue by Icramss** [bapspatil/Pantheon#1]

**Comment by bapspatil** [comment]
Hi, @Icramss. This particular app is in closed beta right now. I'll make it public soon.
In the mean time, my other apps, SilverScreener, FlickOff, and CaptainChef can be found on the Play Store here: [Bapusaheb Patil on the Play Store](https://bit.do/bapsapps)

**Comment by Icramss** [comment]
Thanks , i wait them on future
